apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ly217ro3w-java-springboot
  janus-idp.io/tekton: ly217ro3w-java-springboot
  backstage.io/kubernetes-id: ly217ro3w-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ly217ro3w-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
